
            - name: Web minifier
  # You may pin to the exact commit or the version.
  # uses: zugazagoitia/minify-js@281dbb7bc1fc536317bce869e8b85e0026a3d671
  uses: zugazagoitia/minify-js@v0.4
  with:
    # File to minify, (By default it minifies in all routes)
    directory: # optional
    # Path where the minified files will be saved (By default the minified files will be saved in the original file path)
    output: # optional
          
